version: '3.8'
services: 
  myApi: 
    image: github.com/etozhedin/bulletin_board
    container_name: board_api
    ports:
      - 8001:8000
    restart: always 
    environment: 
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=YourDBName
      - DB_USER=YourDBUser
      - DB_PASSWORD=YourDBPassword
    depends_on:
      - db
  db: 
    image: postgres 
    container_name: board_postgres 
    restart: always 
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pw 
      POSTGRES_DB: db